openapi: 3.1.0
info:
  title: Websocket Chat REST API
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags:
  - name: auth
    description: Authentication
  - name: user
    description: Operations about user
  - name: messages
    description: Chat messaging
security:
  - bearerAuth: [] 
paths:
  /auth/sign:
    post:
      security: []
      tags: [auth, user]
      summary: Auth sign
      description: Logs in a user or registers in case of non existing
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthSign'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        '400':
          description: Unable to sign in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/validate:
    post:
      tags: [auth, user]
      summary: Auth validate
      description: Validates an auth token
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validity'
        '400':
          description: Unable to validate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /auth/refresh:
    post:
      tags: [auth, user]
      summary: Auth Refresh
      description: Refreshes an auth token if the provided one is valid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
        '400':
          description: Unable to validate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    post:
      tags: [messages, user]
      summary: Message
      description: Sends a chat message
      requestBody:
        $ref: '#/components/requestBodies/SendMessage'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '400':
          description: Unable to send message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /user:
    get:
      tags: [user]
      summary: User
      description: Returns the information of the user self()
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Unable to return data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AuthSign:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    Auth:
      type: object
      required: [authToken]
      properties:
        authToken:
          type: string
    Validity:
      type: object
      required: [valid]
      properties:
        valid:
          type: boolean
    Error:
      type: object
      required: [error]
      properties:
        description:
          type: string
    User:
      type: object
      required: [id, username]
      properties:
        id:
          type: string
        username:
          type: string
    Message:
      type: object
      required: [id, senderId, senderName, content]
      properties:
        id:
          type: string
        senderId:
          type: string
        senderName:
          type: string
        content:
          type: string
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: apiKey
      name: Authorization
      in: header
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".
  requestBodies:
    SendMessage:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [content]
            properties:
              content:
                type: string